repos:
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: golangci-lint
    - id: go-build-mod
    - id: go-mod-tidy
- repo: local
  hooks:
    - id: local-build
      name: Locally build
      description: A local make file to always build and test locally
      entry: make build
      files: '\.go$'
      language: 'system'