version: '3'

services:
  profile_db:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=profile
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=profiledatabase
    ports:
      - 5424:5432


  profile_migration:
    build: ./
    depends_on:
      - profile_db
    environment:
      - LOG_LEVEL=debug
      - DO_MIGRATION=true
      - DATABASE_URL=postgres://profile:secret@profile_db:5432/profiledatabase?sslmode=disable
      - CONTACT_ENCRYPTION_KEY=ualgJEcb4GNXLn3jYV9TUGtgYrdTMg
      - CONTACT_ENCRYPTION_SALT=VufLmnycUCgz
    restart: on-failure
