
services:
  profile_database:
    image: paradedb/paradedb:v0.15.0
    environment:
      - POSTGRES_USER=ant
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=service_profile
    ports:
      - "5434:5432"

  profile_migration:
    build: ./
    depends_on:
      - profile_database
    environment:
      - LOG_LEVEL=debug
      - DO_MIGRATION=true
      - DATABASE_URL=postgres://ant:secret@profile_database:5432/service_profile?sslmode=disable
      - CONTACT_ENCRYPTION_KEY=ualgJEcb4GNXLn3jYV9TUGtgYrdTMg
      - CONTACT_ENCRYPTION_SALT=VufLmnycUCgz
    restart: on-failure

#  profile:
#    build: ./
#    depends_on:
#      - profile_database
#      - profile_migration
#    environment:
#      - LOG_LEVEL=debug
#      - DATABASE_URL=postgres://ant:secret@profile_database:5434/service_profile?sslmode=disable
#      - CONTACT_ENCRYPTION_KEY=ualgJEcb4GNXLn3jYV9TUGtgYrdTMg
#      - CONTACT_ENCRYPTION_SALT=VufLmnycUCgz
#      - RUN_SERVICE_SECURELY=false
#      - PORT=8080
#    restart: on-failure
#    ports:
#      - "8080:8080"
