// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: geolocation/v1/geolocation.proto

package geolocationv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/antinvestor/service-profile/proto/geolocation/geolocation/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GeolocationServiceName is the fully-qualified name of the GeolocationService service.
	GeolocationServiceName = "geolocation.v1.GeolocationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GeolocationServiceIngestLocationsProcedure is the fully-qualified name of the
	// GeolocationService's IngestLocations RPC.
	GeolocationServiceIngestLocationsProcedure = "/geolocation.v1.GeolocationService/IngestLocations"
	// GeolocationServiceCreateAreaProcedure is the fully-qualified name of the GeolocationService's
	// CreateArea RPC.
	GeolocationServiceCreateAreaProcedure = "/geolocation.v1.GeolocationService/CreateArea"
	// GeolocationServiceGetAreaProcedure is the fully-qualified name of the GeolocationService's
	// GetArea RPC.
	GeolocationServiceGetAreaProcedure = "/geolocation.v1.GeolocationService/GetArea"
	// GeolocationServiceUpdateAreaProcedure is the fully-qualified name of the GeolocationService's
	// UpdateArea RPC.
	GeolocationServiceUpdateAreaProcedure = "/geolocation.v1.GeolocationService/UpdateArea"
	// GeolocationServiceDeleteAreaProcedure is the fully-qualified name of the GeolocationService's
	// DeleteArea RPC.
	GeolocationServiceDeleteAreaProcedure = "/geolocation.v1.GeolocationService/DeleteArea"
	// GeolocationServiceSearchAreasProcedure is the fully-qualified name of the GeolocationService's
	// SearchAreas RPC.
	GeolocationServiceSearchAreasProcedure = "/geolocation.v1.GeolocationService/SearchAreas"
	// GeolocationServiceCreateRouteProcedure is the fully-qualified name of the GeolocationService's
	// CreateRoute RPC.
	GeolocationServiceCreateRouteProcedure = "/geolocation.v1.GeolocationService/CreateRoute"
	// GeolocationServiceGetRouteProcedure is the fully-qualified name of the GeolocationService's
	// GetRoute RPC.
	GeolocationServiceGetRouteProcedure = "/geolocation.v1.GeolocationService/GetRoute"
	// GeolocationServiceUpdateRouteProcedure is the fully-qualified name of the GeolocationService's
	// UpdateRoute RPC.
	GeolocationServiceUpdateRouteProcedure = "/geolocation.v1.GeolocationService/UpdateRoute"
	// GeolocationServiceDeleteRouteProcedure is the fully-qualified name of the GeolocationService's
	// DeleteRoute RPC.
	GeolocationServiceDeleteRouteProcedure = "/geolocation.v1.GeolocationService/DeleteRoute"
	// GeolocationServiceSearchRoutesProcedure is the fully-qualified name of the GeolocationService's
	// SearchRoutes RPC.
	GeolocationServiceSearchRoutesProcedure = "/geolocation.v1.GeolocationService/SearchRoutes"
	// GeolocationServiceAssignRouteProcedure is the fully-qualified name of the GeolocationService's
	// AssignRoute RPC.
	GeolocationServiceAssignRouteProcedure = "/geolocation.v1.GeolocationService/AssignRoute"
	// GeolocationServiceUnassignRouteProcedure is the fully-qualified name of the GeolocationService's
	// UnassignRoute RPC.
	GeolocationServiceUnassignRouteProcedure = "/geolocation.v1.GeolocationService/UnassignRoute"
	// GeolocationServiceGetSubjectRouteAssignmentsProcedure is the fully-qualified name of the
	// GeolocationService's GetSubjectRouteAssignments RPC.
	GeolocationServiceGetSubjectRouteAssignmentsProcedure = "/geolocation.v1.GeolocationService/GetSubjectRouteAssignments"
	// GeolocationServiceGetTrackProcedure is the fully-qualified name of the GeolocationService's
	// GetTrack RPC.
	GeolocationServiceGetTrackProcedure = "/geolocation.v1.GeolocationService/GetTrack"
	// GeolocationServiceGetSubjectEventsProcedure is the fully-qualified name of the
	// GeolocationService's GetSubjectEvents RPC.
	GeolocationServiceGetSubjectEventsProcedure = "/geolocation.v1.GeolocationService/GetSubjectEvents"
	// GeolocationServiceGetAreaSubjectsProcedure is the fully-qualified name of the
	// GeolocationService's GetAreaSubjects RPC.
	GeolocationServiceGetAreaSubjectsProcedure = "/geolocation.v1.GeolocationService/GetAreaSubjects"
	// GeolocationServiceGetNearbySubjectsProcedure is the fully-qualified name of the
	// GeolocationService's GetNearbySubjects RPC.
	GeolocationServiceGetNearbySubjectsProcedure = "/geolocation.v1.GeolocationService/GetNearbySubjects"
	// GeolocationServiceGetNearbyAreasProcedure is the fully-qualified name of the GeolocationService's
	// GetNearbyAreas RPC.
	GeolocationServiceGetNearbyAreasProcedure = "/geolocation.v1.GeolocationService/GetNearbyAreas"
)

// GeolocationServiceClient is a client for the geolocation.v1.GeolocationService service.
type GeolocationServiceClient interface {
	IngestLocations(context.Context, *connect.Request[v1.IngestLocationsRequest]) (*connect.Response[v1.IngestLocationsResponse], error)
	CreateArea(context.Context, *connect.Request[v1.CreateAreaRequest]) (*connect.Response[v1.CreateAreaResponse], error)
	GetArea(context.Context, *connect.Request[v1.GetAreaRequest]) (*connect.Response[v1.GetAreaResponse], error)
	UpdateArea(context.Context, *connect.Request[v1.UpdateAreaRequest]) (*connect.Response[v1.UpdateAreaResponse], error)
	DeleteArea(context.Context, *connect.Request[v1.DeleteAreaRequest]) (*connect.Response[emptypb.Empty], error)
	SearchAreas(context.Context, *connect.Request[v1.SearchAreasRequest]) (*connect.Response[v1.SearchAreasResponse], error)
	CreateRoute(context.Context, *connect.Request[v1.CreateRouteRequest]) (*connect.Response[v1.CreateRouteResponse], error)
	GetRoute(context.Context, *connect.Request[v1.GetRouteRequest]) (*connect.Response[v1.GetRouteResponse], error)
	UpdateRoute(context.Context, *connect.Request[v1.UpdateRouteRequest]) (*connect.Response[v1.UpdateRouteResponse], error)
	DeleteRoute(context.Context, *connect.Request[v1.DeleteRouteRequest]) (*connect.Response[emptypb.Empty], error)
	SearchRoutes(context.Context, *connect.Request[v1.SearchRoutesRequest]) (*connect.Response[v1.SearchRoutesResponse], error)
	AssignRoute(context.Context, *connect.Request[v1.AssignRouteRequest]) (*connect.Response[v1.AssignRouteResponse], error)
	UnassignRoute(context.Context, *connect.Request[v1.UnassignRouteRequest]) (*connect.Response[emptypb.Empty], error)
	GetSubjectRouteAssignments(context.Context, *connect.Request[v1.GetSubjectRouteAssignmentsRequest]) (*connect.Response[v1.GetSubjectRouteAssignmentsResponse], error)
	GetTrack(context.Context, *connect.Request[v1.GetTrackRequest]) (*connect.Response[v1.GetTrackResponse], error)
	GetSubjectEvents(context.Context, *connect.Request[v1.GetSubjectEventsRequest]) (*connect.Response[v1.GetSubjectEventsResponse], error)
	GetAreaSubjects(context.Context, *connect.Request[v1.GetAreaSubjectsRequest]) (*connect.Response[v1.GetAreaSubjectsResponse], error)
	GetNearbySubjects(context.Context, *connect.Request[v1.GetNearbySubjectsRequest]) (*connect.Response[v1.GetNearbySubjectsResponse], error)
	GetNearbyAreas(context.Context, *connect.Request[v1.GetNearbyAreasRequest]) (*connect.Response[v1.GetNearbyAreasResponse], error)
}

// NewGeolocationServiceClient constructs a client for the geolocation.v1.GeolocationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGeolocationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GeolocationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	geolocationServiceMethods := v1.File_geolocation_v1_geolocation_proto.Services().ByName("GeolocationService").Methods()
	return &geolocationServiceClient{
		ingestLocations: connect.NewClient[v1.IngestLocationsRequest, v1.IngestLocationsResponse](
			httpClient,
			baseURL+GeolocationServiceIngestLocationsProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("IngestLocations")),
			connect.WithClientOptions(opts...),
		),
		createArea: connect.NewClient[v1.CreateAreaRequest, v1.CreateAreaResponse](
			httpClient,
			baseURL+GeolocationServiceCreateAreaProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("CreateArea")),
			connect.WithClientOptions(opts...),
		),
		getArea: connect.NewClient[v1.GetAreaRequest, v1.GetAreaResponse](
			httpClient,
			baseURL+GeolocationServiceGetAreaProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("GetArea")),
			connect.WithClientOptions(opts...),
		),
		updateArea: connect.NewClient[v1.UpdateAreaRequest, v1.UpdateAreaResponse](
			httpClient,
			baseURL+GeolocationServiceUpdateAreaProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("UpdateArea")),
			connect.WithClientOptions(opts...),
		),
		deleteArea: connect.NewClient[v1.DeleteAreaRequest, emptypb.Empty](
			httpClient,
			baseURL+GeolocationServiceDeleteAreaProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("DeleteArea")),
			connect.WithClientOptions(opts...),
		),
		searchAreas: connect.NewClient[v1.SearchAreasRequest, v1.SearchAreasResponse](
			httpClient,
			baseURL+GeolocationServiceSearchAreasProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("SearchAreas")),
			connect.WithClientOptions(opts...),
		),
		createRoute: connect.NewClient[v1.CreateRouteRequest, v1.CreateRouteResponse](
			httpClient,
			baseURL+GeolocationServiceCreateRouteProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("CreateRoute")),
			connect.WithClientOptions(opts...),
		),
		getRoute: connect.NewClient[v1.GetRouteRequest, v1.GetRouteResponse](
			httpClient,
			baseURL+GeolocationServiceGetRouteProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("GetRoute")),
			connect.WithClientOptions(opts...),
		),
		updateRoute: connect.NewClient[v1.UpdateRouteRequest, v1.UpdateRouteResponse](
			httpClient,
			baseURL+GeolocationServiceUpdateRouteProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("UpdateRoute")),
			connect.WithClientOptions(opts...),
		),
		deleteRoute: connect.NewClient[v1.DeleteRouteRequest, emptypb.Empty](
			httpClient,
			baseURL+GeolocationServiceDeleteRouteProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("DeleteRoute")),
			connect.WithClientOptions(opts...),
		),
		searchRoutes: connect.NewClient[v1.SearchRoutesRequest, v1.SearchRoutesResponse](
			httpClient,
			baseURL+GeolocationServiceSearchRoutesProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("SearchRoutes")),
			connect.WithClientOptions(opts...),
		),
		assignRoute: connect.NewClient[v1.AssignRouteRequest, v1.AssignRouteResponse](
			httpClient,
			baseURL+GeolocationServiceAssignRouteProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("AssignRoute")),
			connect.WithClientOptions(opts...),
		),
		unassignRoute: connect.NewClient[v1.UnassignRouteRequest, emptypb.Empty](
			httpClient,
			baseURL+GeolocationServiceUnassignRouteProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("UnassignRoute")),
			connect.WithClientOptions(opts...),
		),
		getSubjectRouteAssignments: connect.NewClient[v1.GetSubjectRouteAssignmentsRequest, v1.GetSubjectRouteAssignmentsResponse](
			httpClient,
			baseURL+GeolocationServiceGetSubjectRouteAssignmentsProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("GetSubjectRouteAssignments")),
			connect.WithClientOptions(opts...),
		),
		getTrack: connect.NewClient[v1.GetTrackRequest, v1.GetTrackResponse](
			httpClient,
			baseURL+GeolocationServiceGetTrackProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("GetTrack")),
			connect.WithClientOptions(opts...),
		),
		getSubjectEvents: connect.NewClient[v1.GetSubjectEventsRequest, v1.GetSubjectEventsResponse](
			httpClient,
			baseURL+GeolocationServiceGetSubjectEventsProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("GetSubjectEvents")),
			connect.WithClientOptions(opts...),
		),
		getAreaSubjects: connect.NewClient[v1.GetAreaSubjectsRequest, v1.GetAreaSubjectsResponse](
			httpClient,
			baseURL+GeolocationServiceGetAreaSubjectsProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("GetAreaSubjects")),
			connect.WithClientOptions(opts...),
		),
		getNearbySubjects: connect.NewClient[v1.GetNearbySubjectsRequest, v1.GetNearbySubjectsResponse](
			httpClient,
			baseURL+GeolocationServiceGetNearbySubjectsProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("GetNearbySubjects")),
			connect.WithClientOptions(opts...),
		),
		getNearbyAreas: connect.NewClient[v1.GetNearbyAreasRequest, v1.GetNearbyAreasResponse](
			httpClient,
			baseURL+GeolocationServiceGetNearbyAreasProcedure,
			connect.WithSchema(geolocationServiceMethods.ByName("GetNearbyAreas")),
			connect.WithClientOptions(opts...),
		),
	}
}

// geolocationServiceClient implements GeolocationServiceClient.
type geolocationServiceClient struct {
	ingestLocations            *connect.Client[v1.IngestLocationsRequest, v1.IngestLocationsResponse]
	createArea                 *connect.Client[v1.CreateAreaRequest, v1.CreateAreaResponse]
	getArea                    *connect.Client[v1.GetAreaRequest, v1.GetAreaResponse]
	updateArea                 *connect.Client[v1.UpdateAreaRequest, v1.UpdateAreaResponse]
	deleteArea                 *connect.Client[v1.DeleteAreaRequest, emptypb.Empty]
	searchAreas                *connect.Client[v1.SearchAreasRequest, v1.SearchAreasResponse]
	createRoute                *connect.Client[v1.CreateRouteRequest, v1.CreateRouteResponse]
	getRoute                   *connect.Client[v1.GetRouteRequest, v1.GetRouteResponse]
	updateRoute                *connect.Client[v1.UpdateRouteRequest, v1.UpdateRouteResponse]
	deleteRoute                *connect.Client[v1.DeleteRouteRequest, emptypb.Empty]
	searchRoutes               *connect.Client[v1.SearchRoutesRequest, v1.SearchRoutesResponse]
	assignRoute                *connect.Client[v1.AssignRouteRequest, v1.AssignRouteResponse]
	unassignRoute              *connect.Client[v1.UnassignRouteRequest, emptypb.Empty]
	getSubjectRouteAssignments *connect.Client[v1.GetSubjectRouteAssignmentsRequest, v1.GetSubjectRouteAssignmentsResponse]
	getTrack                   *connect.Client[v1.GetTrackRequest, v1.GetTrackResponse]
	getSubjectEvents           *connect.Client[v1.GetSubjectEventsRequest, v1.GetSubjectEventsResponse]
	getAreaSubjects            *connect.Client[v1.GetAreaSubjectsRequest, v1.GetAreaSubjectsResponse]
	getNearbySubjects          *connect.Client[v1.GetNearbySubjectsRequest, v1.GetNearbySubjectsResponse]
	getNearbyAreas             *connect.Client[v1.GetNearbyAreasRequest, v1.GetNearbyAreasResponse]
}

// IngestLocations calls geolocation.v1.GeolocationService.IngestLocations.
func (c *geolocationServiceClient) IngestLocations(ctx context.Context, req *connect.Request[v1.IngestLocationsRequest]) (*connect.Response[v1.IngestLocationsResponse], error) {
	return c.ingestLocations.CallUnary(ctx, req)
}

// CreateArea calls geolocation.v1.GeolocationService.CreateArea.
func (c *geolocationServiceClient) CreateArea(ctx context.Context, req *connect.Request[v1.CreateAreaRequest]) (*connect.Response[v1.CreateAreaResponse], error) {
	return c.createArea.CallUnary(ctx, req)
}

// GetArea calls geolocation.v1.GeolocationService.GetArea.
func (c *geolocationServiceClient) GetArea(ctx context.Context, req *connect.Request[v1.GetAreaRequest]) (*connect.Response[v1.GetAreaResponse], error) {
	return c.getArea.CallUnary(ctx, req)
}

// UpdateArea calls geolocation.v1.GeolocationService.UpdateArea.
func (c *geolocationServiceClient) UpdateArea(ctx context.Context, req *connect.Request[v1.UpdateAreaRequest]) (*connect.Response[v1.UpdateAreaResponse], error) {
	return c.updateArea.CallUnary(ctx, req)
}

// DeleteArea calls geolocation.v1.GeolocationService.DeleteArea.
func (c *geolocationServiceClient) DeleteArea(ctx context.Context, req *connect.Request[v1.DeleteAreaRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteArea.CallUnary(ctx, req)
}

// SearchAreas calls geolocation.v1.GeolocationService.SearchAreas.
func (c *geolocationServiceClient) SearchAreas(ctx context.Context, req *connect.Request[v1.SearchAreasRequest]) (*connect.Response[v1.SearchAreasResponse], error) {
	return c.searchAreas.CallUnary(ctx, req)
}

// CreateRoute calls geolocation.v1.GeolocationService.CreateRoute.
func (c *geolocationServiceClient) CreateRoute(ctx context.Context, req *connect.Request[v1.CreateRouteRequest]) (*connect.Response[v1.CreateRouteResponse], error) {
	return c.createRoute.CallUnary(ctx, req)
}

// GetRoute calls geolocation.v1.GeolocationService.GetRoute.
func (c *geolocationServiceClient) GetRoute(ctx context.Context, req *connect.Request[v1.GetRouteRequest]) (*connect.Response[v1.GetRouteResponse], error) {
	return c.getRoute.CallUnary(ctx, req)
}

// UpdateRoute calls geolocation.v1.GeolocationService.UpdateRoute.
func (c *geolocationServiceClient) UpdateRoute(ctx context.Context, req *connect.Request[v1.UpdateRouteRequest]) (*connect.Response[v1.UpdateRouteResponse], error) {
	return c.updateRoute.CallUnary(ctx, req)
}

// DeleteRoute calls geolocation.v1.GeolocationService.DeleteRoute.
func (c *geolocationServiceClient) DeleteRoute(ctx context.Context, req *connect.Request[v1.DeleteRouteRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteRoute.CallUnary(ctx, req)
}

// SearchRoutes calls geolocation.v1.GeolocationService.SearchRoutes.
func (c *geolocationServiceClient) SearchRoutes(ctx context.Context, req *connect.Request[v1.SearchRoutesRequest]) (*connect.Response[v1.SearchRoutesResponse], error) {
	return c.searchRoutes.CallUnary(ctx, req)
}

// AssignRoute calls geolocation.v1.GeolocationService.AssignRoute.
func (c *geolocationServiceClient) AssignRoute(ctx context.Context, req *connect.Request[v1.AssignRouteRequest]) (*connect.Response[v1.AssignRouteResponse], error) {
	return c.assignRoute.CallUnary(ctx, req)
}

// UnassignRoute calls geolocation.v1.GeolocationService.UnassignRoute.
func (c *geolocationServiceClient) UnassignRoute(ctx context.Context, req *connect.Request[v1.UnassignRouteRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.unassignRoute.CallUnary(ctx, req)
}

// GetSubjectRouteAssignments calls geolocation.v1.GeolocationService.GetSubjectRouteAssignments.
func (c *geolocationServiceClient) GetSubjectRouteAssignments(ctx context.Context, req *connect.Request[v1.GetSubjectRouteAssignmentsRequest]) (*connect.Response[v1.GetSubjectRouteAssignmentsResponse], error) {
	return c.getSubjectRouteAssignments.CallUnary(ctx, req)
}

// GetTrack calls geolocation.v1.GeolocationService.GetTrack.
func (c *geolocationServiceClient) GetTrack(ctx context.Context, req *connect.Request[v1.GetTrackRequest]) (*connect.Response[v1.GetTrackResponse], error) {
	return c.getTrack.CallUnary(ctx, req)
}

// GetSubjectEvents calls geolocation.v1.GeolocationService.GetSubjectEvents.
func (c *geolocationServiceClient) GetSubjectEvents(ctx context.Context, req *connect.Request[v1.GetSubjectEventsRequest]) (*connect.Response[v1.GetSubjectEventsResponse], error) {
	return c.getSubjectEvents.CallUnary(ctx, req)
}

// GetAreaSubjects calls geolocation.v1.GeolocationService.GetAreaSubjects.
func (c *geolocationServiceClient) GetAreaSubjects(ctx context.Context, req *connect.Request[v1.GetAreaSubjectsRequest]) (*connect.Response[v1.GetAreaSubjectsResponse], error) {
	return c.getAreaSubjects.CallUnary(ctx, req)
}

// GetNearbySubjects calls geolocation.v1.GeolocationService.GetNearbySubjects.
func (c *geolocationServiceClient) GetNearbySubjects(ctx context.Context, req *connect.Request[v1.GetNearbySubjectsRequest]) (*connect.Response[v1.GetNearbySubjectsResponse], error) {
	return c.getNearbySubjects.CallUnary(ctx, req)
}

// GetNearbyAreas calls geolocation.v1.GeolocationService.GetNearbyAreas.
func (c *geolocationServiceClient) GetNearbyAreas(ctx context.Context, req *connect.Request[v1.GetNearbyAreasRequest]) (*connect.Response[v1.GetNearbyAreasResponse], error) {
	return c.getNearbyAreas.CallUnary(ctx, req)
}

// GeolocationServiceHandler is an implementation of the geolocation.v1.GeolocationService service.
type GeolocationServiceHandler interface {
	IngestLocations(context.Context, *connect.Request[v1.IngestLocationsRequest]) (*connect.Response[v1.IngestLocationsResponse], error)
	CreateArea(context.Context, *connect.Request[v1.CreateAreaRequest]) (*connect.Response[v1.CreateAreaResponse], error)
	GetArea(context.Context, *connect.Request[v1.GetAreaRequest]) (*connect.Response[v1.GetAreaResponse], error)
	UpdateArea(context.Context, *connect.Request[v1.UpdateAreaRequest]) (*connect.Response[v1.UpdateAreaResponse], error)
	DeleteArea(context.Context, *connect.Request[v1.DeleteAreaRequest]) (*connect.Response[emptypb.Empty], error)
	SearchAreas(context.Context, *connect.Request[v1.SearchAreasRequest]) (*connect.Response[v1.SearchAreasResponse], error)
	CreateRoute(context.Context, *connect.Request[v1.CreateRouteRequest]) (*connect.Response[v1.CreateRouteResponse], error)
	GetRoute(context.Context, *connect.Request[v1.GetRouteRequest]) (*connect.Response[v1.GetRouteResponse], error)
	UpdateRoute(context.Context, *connect.Request[v1.UpdateRouteRequest]) (*connect.Response[v1.UpdateRouteResponse], error)
	DeleteRoute(context.Context, *connect.Request[v1.DeleteRouteRequest]) (*connect.Response[emptypb.Empty], error)
	SearchRoutes(context.Context, *connect.Request[v1.SearchRoutesRequest]) (*connect.Response[v1.SearchRoutesResponse], error)
	AssignRoute(context.Context, *connect.Request[v1.AssignRouteRequest]) (*connect.Response[v1.AssignRouteResponse], error)
	UnassignRoute(context.Context, *connect.Request[v1.UnassignRouteRequest]) (*connect.Response[emptypb.Empty], error)
	GetSubjectRouteAssignments(context.Context, *connect.Request[v1.GetSubjectRouteAssignmentsRequest]) (*connect.Response[v1.GetSubjectRouteAssignmentsResponse], error)
	GetTrack(context.Context, *connect.Request[v1.GetTrackRequest]) (*connect.Response[v1.GetTrackResponse], error)
	GetSubjectEvents(context.Context, *connect.Request[v1.GetSubjectEventsRequest]) (*connect.Response[v1.GetSubjectEventsResponse], error)
	GetAreaSubjects(context.Context, *connect.Request[v1.GetAreaSubjectsRequest]) (*connect.Response[v1.GetAreaSubjectsResponse], error)
	GetNearbySubjects(context.Context, *connect.Request[v1.GetNearbySubjectsRequest]) (*connect.Response[v1.GetNearbySubjectsResponse], error)
	GetNearbyAreas(context.Context, *connect.Request[v1.GetNearbyAreasRequest]) (*connect.Response[v1.GetNearbyAreasResponse], error)
}

// NewGeolocationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGeolocationServiceHandler(svc GeolocationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	geolocationServiceMethods := v1.File_geolocation_v1_geolocation_proto.Services().ByName("GeolocationService").Methods()
	geolocationServiceIngestLocationsHandler := connect.NewUnaryHandler(
		GeolocationServiceIngestLocationsProcedure,
		svc.IngestLocations,
		connect.WithSchema(geolocationServiceMethods.ByName("IngestLocations")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceCreateAreaHandler := connect.NewUnaryHandler(
		GeolocationServiceCreateAreaProcedure,
		svc.CreateArea,
		connect.WithSchema(geolocationServiceMethods.ByName("CreateArea")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceGetAreaHandler := connect.NewUnaryHandler(
		GeolocationServiceGetAreaProcedure,
		svc.GetArea,
		connect.WithSchema(geolocationServiceMethods.ByName("GetArea")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceUpdateAreaHandler := connect.NewUnaryHandler(
		GeolocationServiceUpdateAreaProcedure,
		svc.UpdateArea,
		connect.WithSchema(geolocationServiceMethods.ByName("UpdateArea")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceDeleteAreaHandler := connect.NewUnaryHandler(
		GeolocationServiceDeleteAreaProcedure,
		svc.DeleteArea,
		connect.WithSchema(geolocationServiceMethods.ByName("DeleteArea")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceSearchAreasHandler := connect.NewUnaryHandler(
		GeolocationServiceSearchAreasProcedure,
		svc.SearchAreas,
		connect.WithSchema(geolocationServiceMethods.ByName("SearchAreas")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceCreateRouteHandler := connect.NewUnaryHandler(
		GeolocationServiceCreateRouteProcedure,
		svc.CreateRoute,
		connect.WithSchema(geolocationServiceMethods.ByName("CreateRoute")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceGetRouteHandler := connect.NewUnaryHandler(
		GeolocationServiceGetRouteProcedure,
		svc.GetRoute,
		connect.WithSchema(geolocationServiceMethods.ByName("GetRoute")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceUpdateRouteHandler := connect.NewUnaryHandler(
		GeolocationServiceUpdateRouteProcedure,
		svc.UpdateRoute,
		connect.WithSchema(geolocationServiceMethods.ByName("UpdateRoute")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceDeleteRouteHandler := connect.NewUnaryHandler(
		GeolocationServiceDeleteRouteProcedure,
		svc.DeleteRoute,
		connect.WithSchema(geolocationServiceMethods.ByName("DeleteRoute")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceSearchRoutesHandler := connect.NewUnaryHandler(
		GeolocationServiceSearchRoutesProcedure,
		svc.SearchRoutes,
		connect.WithSchema(geolocationServiceMethods.ByName("SearchRoutes")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceAssignRouteHandler := connect.NewUnaryHandler(
		GeolocationServiceAssignRouteProcedure,
		svc.AssignRoute,
		connect.WithSchema(geolocationServiceMethods.ByName("AssignRoute")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceUnassignRouteHandler := connect.NewUnaryHandler(
		GeolocationServiceUnassignRouteProcedure,
		svc.UnassignRoute,
		connect.WithSchema(geolocationServiceMethods.ByName("UnassignRoute")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceGetSubjectRouteAssignmentsHandler := connect.NewUnaryHandler(
		GeolocationServiceGetSubjectRouteAssignmentsProcedure,
		svc.GetSubjectRouteAssignments,
		connect.WithSchema(geolocationServiceMethods.ByName("GetSubjectRouteAssignments")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceGetTrackHandler := connect.NewUnaryHandler(
		GeolocationServiceGetTrackProcedure,
		svc.GetTrack,
		connect.WithSchema(geolocationServiceMethods.ByName("GetTrack")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceGetSubjectEventsHandler := connect.NewUnaryHandler(
		GeolocationServiceGetSubjectEventsProcedure,
		svc.GetSubjectEvents,
		connect.WithSchema(geolocationServiceMethods.ByName("GetSubjectEvents")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceGetAreaSubjectsHandler := connect.NewUnaryHandler(
		GeolocationServiceGetAreaSubjectsProcedure,
		svc.GetAreaSubjects,
		connect.WithSchema(geolocationServiceMethods.ByName("GetAreaSubjects")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceGetNearbySubjectsHandler := connect.NewUnaryHandler(
		GeolocationServiceGetNearbySubjectsProcedure,
		svc.GetNearbySubjects,
		connect.WithSchema(geolocationServiceMethods.ByName("GetNearbySubjects")),
		connect.WithHandlerOptions(opts...),
	)
	geolocationServiceGetNearbyAreasHandler := connect.NewUnaryHandler(
		GeolocationServiceGetNearbyAreasProcedure,
		svc.GetNearbyAreas,
		connect.WithSchema(geolocationServiceMethods.ByName("GetNearbyAreas")),
		connect.WithHandlerOptions(opts...),
	)
	return "/geolocation.v1.GeolocationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GeolocationServiceIngestLocationsProcedure:
			geolocationServiceIngestLocationsHandler.ServeHTTP(w, r)
		case GeolocationServiceCreateAreaProcedure:
			geolocationServiceCreateAreaHandler.ServeHTTP(w, r)
		case GeolocationServiceGetAreaProcedure:
			geolocationServiceGetAreaHandler.ServeHTTP(w, r)
		case GeolocationServiceUpdateAreaProcedure:
			geolocationServiceUpdateAreaHandler.ServeHTTP(w, r)
		case GeolocationServiceDeleteAreaProcedure:
			geolocationServiceDeleteAreaHandler.ServeHTTP(w, r)
		case GeolocationServiceSearchAreasProcedure:
			geolocationServiceSearchAreasHandler.ServeHTTP(w, r)
		case GeolocationServiceCreateRouteProcedure:
			geolocationServiceCreateRouteHandler.ServeHTTP(w, r)
		case GeolocationServiceGetRouteProcedure:
			geolocationServiceGetRouteHandler.ServeHTTP(w, r)
		case GeolocationServiceUpdateRouteProcedure:
			geolocationServiceUpdateRouteHandler.ServeHTTP(w, r)
		case GeolocationServiceDeleteRouteProcedure:
			geolocationServiceDeleteRouteHandler.ServeHTTP(w, r)
		case GeolocationServiceSearchRoutesProcedure:
			geolocationServiceSearchRoutesHandler.ServeHTTP(w, r)
		case GeolocationServiceAssignRouteProcedure:
			geolocationServiceAssignRouteHandler.ServeHTTP(w, r)
		case GeolocationServiceUnassignRouteProcedure:
			geolocationServiceUnassignRouteHandler.ServeHTTP(w, r)
		case GeolocationServiceGetSubjectRouteAssignmentsProcedure:
			geolocationServiceGetSubjectRouteAssignmentsHandler.ServeHTTP(w, r)
		case GeolocationServiceGetTrackProcedure:
			geolocationServiceGetTrackHandler.ServeHTTP(w, r)
		case GeolocationServiceGetSubjectEventsProcedure:
			geolocationServiceGetSubjectEventsHandler.ServeHTTP(w, r)
		case GeolocationServiceGetAreaSubjectsProcedure:
			geolocationServiceGetAreaSubjectsHandler.ServeHTTP(w, r)
		case GeolocationServiceGetNearbySubjectsProcedure:
			geolocationServiceGetNearbySubjectsHandler.ServeHTTP(w, r)
		case GeolocationServiceGetNearbyAreasProcedure:
			geolocationServiceGetNearbyAreasHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGeolocationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGeolocationServiceHandler struct{}

func (UnimplementedGeolocationServiceHandler) IngestLocations(context.Context, *connect.Request[v1.IngestLocationsRequest]) (*connect.Response[v1.IngestLocationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.IngestLocations is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) CreateArea(context.Context, *connect.Request[v1.CreateAreaRequest]) (*connect.Response[v1.CreateAreaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.CreateArea is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) GetArea(context.Context, *connect.Request[v1.GetAreaRequest]) (*connect.Response[v1.GetAreaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.GetArea is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) UpdateArea(context.Context, *connect.Request[v1.UpdateAreaRequest]) (*connect.Response[v1.UpdateAreaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.UpdateArea is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) DeleteArea(context.Context, *connect.Request[v1.DeleteAreaRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.DeleteArea is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) SearchAreas(context.Context, *connect.Request[v1.SearchAreasRequest]) (*connect.Response[v1.SearchAreasResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.SearchAreas is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) CreateRoute(context.Context, *connect.Request[v1.CreateRouteRequest]) (*connect.Response[v1.CreateRouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.CreateRoute is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) GetRoute(context.Context, *connect.Request[v1.GetRouteRequest]) (*connect.Response[v1.GetRouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.GetRoute is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) UpdateRoute(context.Context, *connect.Request[v1.UpdateRouteRequest]) (*connect.Response[v1.UpdateRouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.UpdateRoute is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) DeleteRoute(context.Context, *connect.Request[v1.DeleteRouteRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.DeleteRoute is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) SearchRoutes(context.Context, *connect.Request[v1.SearchRoutesRequest]) (*connect.Response[v1.SearchRoutesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.SearchRoutes is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) AssignRoute(context.Context, *connect.Request[v1.AssignRouteRequest]) (*connect.Response[v1.AssignRouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.AssignRoute is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) UnassignRoute(context.Context, *connect.Request[v1.UnassignRouteRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.UnassignRoute is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) GetSubjectRouteAssignments(context.Context, *connect.Request[v1.GetSubjectRouteAssignmentsRequest]) (*connect.Response[v1.GetSubjectRouteAssignmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.GetSubjectRouteAssignments is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) GetTrack(context.Context, *connect.Request[v1.GetTrackRequest]) (*connect.Response[v1.GetTrackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.GetTrack is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) GetSubjectEvents(context.Context, *connect.Request[v1.GetSubjectEventsRequest]) (*connect.Response[v1.GetSubjectEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.GetSubjectEvents is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) GetAreaSubjects(context.Context, *connect.Request[v1.GetAreaSubjectsRequest]) (*connect.Response[v1.GetAreaSubjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.GetAreaSubjects is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) GetNearbySubjects(context.Context, *connect.Request[v1.GetNearbySubjectsRequest]) (*connect.Response[v1.GetNearbySubjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.GetNearbySubjects is not implemented"))
}

func (UnimplementedGeolocationServiceHandler) GetNearbyAreas(context.Context, *connect.Request[v1.GetNearbyAreasRequest]) (*connect.Response[v1.GetNearbyAreasResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("geolocation.v1.GeolocationService.GetNearbyAreas is not implemented"))
}
