//
//  Generated code. Do not modify.
//  source: device/v1/device.proto
//

import "package:connectrpc/connect.dart" as connect;
import "device.pb.dart" as devicev1device;

/// DeviceService provides core device management and key/token management.
/// All RPCs require authentication via Bearer token unless otherwise specified.
abstract final class DeviceService {
  /// Fully-qualified name of the DeviceService service.
  static const name = 'device.v1.DeviceService';

  /// GetById retrieves one or more devices by their unique identifiers.
  /// Supports batch retrieval for efficiency.
  static const getById = connect.Spec(
    '/$name/GetById',
    connect.StreamType.unary,
    devicev1device.GetByIdRequest.new,
    devicev1device.GetByIdResponse.new,
    idempotency: connect.Idempotency.noSideEffects,
  );

  /// GetBySessionId retrieves a device by its active session identifier.
  /// Useful for resolving devices from session tokens.
  static const getBySessionId = connect.Spec(
    '/$name/GetBySessionId',
    connect.StreamType.unary,
    devicev1device.GetBySessionIdRequest.new,
    devicev1device.GetBySessionIdResponse.new,
    idempotency: connect.Idempotency.noSideEffects,
  );

  /// Search finds devices matching specified criteria.
  /// Supports filtering by date range, properties, and full-text search.
  static const search = connect.Spec(
    '/$name/Search',
    connect.StreamType.server,
    devicev1device.SearchRequest.new,
    devicev1device.SearchResponse.new,
    idempotency: connect.Idempotency.noSideEffects,
  );

  /// Create registers a new device in the system.
  /// Returns a unique device ID that should be stored by the client.
  static const create = connect.Spec(
    '/$name/Create',
    connect.StreamType.unary,
    devicev1device.CreateRequest.new,
    devicev1device.CreateResponse.new,
  );

  /// Update modifies an existing device's information.
  /// Only the device owner or administrators can update device information.
  static const update = connect.Spec(
    '/$name/Update',
    connect.StreamType.unary,
    devicev1device.UpdateRequest.new,
    devicev1device.UpdateResponse.new,
  );

  /// Link associates a device with a user profile.
  /// Required before the device can be used for authenticated operations.
  static const link = connect.Spec(
    '/$name/Link',
    connect.StreamType.unary,
    devicev1device.LinkRequest.new,
    devicev1device.LinkResponse.new,
  );

  /// Remove deletes a device from the system.
  /// This operation cannot be undone.
  static const remove = connect.Spec(
    '/$name/Remove',
    connect.StreamType.unary,
    devicev1device.RemoveRequest.new,
    devicev1device.RemoveResponse.new,
  );

  /// Log creates a new activity log entry for a device.
  /// Used for session tracking and security auditing.
  static const log = connect.Spec(
    '/$name/Log',
    connect.StreamType.unary,
    devicev1device.LogRequest.new,
    devicev1device.LogResponse.new,
  );

  /// ListLogs retrieves activity logs for a device.
  /// Returns a stream of log entries for the specified device.
  static const listLogs = connect.Spec(
    '/$name/ListLogs',
    connect.StreamType.server,
    devicev1device.ListLogsRequest.new,
    devicev1device.ListLogsResponse.new,
    idempotency: connect.Idempotency.noSideEffects,
  );

  /// AddKey stores a key or token and its material in the local storage for a device.
  /// This is used for keys generated by the service or when the service needs to manage the key material directly.
  static const addKey = connect.Spec(
    '/$name/AddKey',
    connect.StreamType.unary,
    devicev1device.AddKeyRequest.new,
    devicev1device.AddKeyResponse.new,
  );

  /// RemoveKey removes one or more keys or tokens from local storage.
  /// This does not handle deregistration from third-party services. For that, use DeRegisterKey.
  static const removeKey = connect.Spec(
    '/$name/RemoveKey',
    connect.StreamType.unary,
    devicev1device.RemoveKeyRequest.new,
    devicev1device.RemoveKeyResponse.new,
  );

  /// SearchKey searches for keys or tokens associated with a device.
  static const searchKey = connect.Spec(
    '/$name/SearchKey',
    connect.StreamType.unary,
    devicev1device.SearchKeyRequest.new,
    devicev1device.SearchKeyResponse.new,
    idempotency: connect.Idempotency.noSideEffects,
  );

  /// RegisterKey registers a key with a third-party service using an externally-generated key or token.
  /// This method handles the integration with the external service and stores metadata about the key,
  /// but not the key material itself. Use AddKey to store key material.
  static const registerKey = connect.Spec(
    '/$name/RegisterKey',
    connect.StreamType.unary,
    devicev1device.RegisterKeyRequest.new,
    devicev1device.RegisterKeyResponse.new,
  );

  /// DeRegisterKey deregisters a key from a third-party service.
  /// This handles cleanup with the external service and removes the associated key metadata from local storage.
  static const deRegisterKey = connect.Spec(
    '/$name/DeRegisterKey',
    connect.StreamType.unary,
    devicev1device.DeRegisterKeyRequest.new,
    devicev1device.DeRegisterKeyResponse.new,
  );

  /// Returns short-lived TURN server credentials for WebRTC media relay.
  /// Credentials are generated per-request with a configurable TTL.
  /// The server should generate HMAC-based credentials using a shared
  /// secret with the TURN server (RFC 5766 long-term credentials).
  static const getTurnCredentials = connect.Spec(
    '/$name/GetTurnCredentials',
    connect.StreamType.unary,
    devicev1device.GetTurnCredentialsRequest.new,
    devicev1device.GetTurnCredentialsResponse.new,
  );

  /// Notify sends a notification to a device using one of its registered keys.
  /// The service selects an appropriate key based on key_type (e.g., FCM_TOKEN for push notifications).
  /// If key_id is provided, that specific key will be used; otherwise the service selects the best available key.
  static const notify = connect.Spec(
    '/$name/Notify',
    connect.StreamType.unary,
    devicev1device.NotifyRequest.new,
    devicev1device.NotifyResponse.new,
  );

  /// UpdatePresence updates the presence status of a device.
  /// Used to track online/offline status and availability for real-time features.
  static const updatePresence = connect.Spec(
    '/$name/UpdatePresence',
    connect.StreamType.unary,
    devicev1device.UpdatePresenceRequest.new,
    devicev1device.UpdatePresenceResponse.new,
  );
}
