// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package profile

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContactType int32

const (
	ContactType_EMAIL ContactType = 0
	ContactType_PHONE ContactType = 1
)

var ContactType_name = map[int32]string{
	0: "EMAIL",
	1: "PHONE",
}

var ContactType_value = map[string]int32{
	"EMAIL": 0,
	"PHONE": 1,
}

func (x ContactType) String() string {
	return proto.EnumName(ContactType_name, int32(x))
}

func (ContactType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

type CommunicationLevel int32

const (
	CommunicationLevel_ALL                CommunicationLevel = 0
	CommunicationLevel_INTERNAL_MARKETING CommunicationLevel = 1
	CommunicationLevel_IMPORTANT_ALERTS   CommunicationLevel = 2
	CommunicationLevel_SYSTEM_ALERTS      CommunicationLevel = 3
	CommunicationLevel_NO_CONTACT         CommunicationLevel = 4
)

var CommunicationLevel_name = map[int32]string{
	0: "ALL",
	1: "INTERNAL_MARKETING",
	2: "IMPORTANT_ALERTS",
	3: "SYSTEM_ALERTS",
	4: "NO_CONTACT",
}

var CommunicationLevel_value = map[string]int32{
	"ALL":                0,
	"INTERNAL_MARKETING": 1,
	"IMPORTANT_ALERTS":   2,
	"SYSTEM_ALERTS":      3,
	"NO_CONTACT":         4,
}

func (x CommunicationLevel) String() string {
	return proto.EnumName(CommunicationLevel_name, int32(x))
}

func (CommunicationLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

type ProfileType int32

const (
	ProfileType_PERSON      ProfileType = 0
	ProfileType_INSTITUTION ProfileType = 1
	ProfileType_BOT         ProfileType = 2
)

var ProfileType_name = map[int32]string{
	0: "PERSON",
	1: "INSTITUTION",
	2: "BOT",
}

var ProfileType_value = map[string]int32{
	"PERSON":      0,
	"INSTITUTION": 1,
	"BOT":         2,
}

func (x ProfileType) String() string {
	return proto.EnumName(ProfileType_name, int32(x))
}

func (ProfileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{2}
}

type ContactObject struct {
	ID                   string             `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 ContactType        `protobuf:"varint,2,opt,name=type,proto3,enum=profile.ContactType" json:"type,omitempty"`
	Detail               string             `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Verifed              bool               `protobuf:"varint,4,opt,name=verifed,proto3" json:"verifed,omitempty"`
	CommunicationLevel   CommunicationLevel `protobuf:"varint,5,opt,name=communication_level,json=communicationLevel,proto3,enum=profile.CommunicationLevel" json:"communication_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ContactObject) Reset()         { *m = ContactObject{} }
func (m *ContactObject) String() string { return proto.CompactTextString(m) }
func (*ContactObject) ProtoMessage()    {}
func (*ContactObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *ContactObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactObject.Unmarshal(m, b)
}
func (m *ContactObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactObject.Marshal(b, m, deterministic)
}
func (m *ContactObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactObject.Merge(m, src)
}
func (m *ContactObject) XXX_Size() int {
	return xxx_messageInfo_ContactObject.Size(m)
}
func (m *ContactObject) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactObject.DiscardUnknown(m)
}

var xxx_messageInfo_ContactObject proto.InternalMessageInfo

func (m *ContactObject) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ContactObject) GetType() ContactType {
	if m != nil {
		return m.Type
	}
	return ContactType_EMAIL
}

func (m *ContactObject) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *ContactObject) GetVerifed() bool {
	if m != nil {
		return m.Verifed
	}
	return false
}

func (m *ContactObject) GetCommunicationLevel() CommunicationLevel {
	if m != nil {
		return m.CommunicationLevel
	}
	return CommunicationLevel_ALL
}

type AddressObject struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Area                 string   `protobuf:"bytes,5,opt,name=area,proto3" json:"area,omitempty"`
	Street               string   `protobuf:"bytes,6,opt,name=street,proto3" json:"street,omitempty"`
	House                string   `protobuf:"bytes,7,opt,name=house,proto3" json:"house,omitempty"`
	Postcode             string   `protobuf:"bytes,8,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Latitude             float64  `protobuf:"fixed64,9,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,10,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Extra                string   `protobuf:"bytes,11,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressObject) Reset()         { *m = AddressObject{} }
func (m *AddressObject) String() string { return proto.CompactTextString(m) }
func (*AddressObject) ProtoMessage()    {}
func (*AddressObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *AddressObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressObject.Unmarshal(m, b)
}
func (m *AddressObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressObject.Marshal(b, m, deterministic)
}
func (m *AddressObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressObject.Merge(m, src)
}
func (m *AddressObject) XXX_Size() int {
	return xxx_messageInfo_AddressObject.Size(m)
}
func (m *AddressObject) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressObject.DiscardUnknown(m)
}

var xxx_messageInfo_AddressObject proto.InternalMessageInfo

func (m *AddressObject) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AddressObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddressObject) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *AddressObject) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *AddressObject) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *AddressObject) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *AddressObject) GetHouse() string {
	if m != nil {
		return m.House
	}
	return ""
}

func (m *AddressObject) GetPostcode() string {
	if m != nil {
		return m.Postcode
	}
	return ""
}

func (m *AddressObject) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *AddressObject) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *AddressObject) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

// The response message containing the greetings
type ProfileObject struct {
	ID                   string            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 ProfileType       `protobuf:"varint,2,opt,name=type,proto3,enum=profile.ProfileType" json:"type,omitempty"`
	Properties           map[string]string `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Contacts             []*ContactObject  `protobuf:"bytes,4,rep,name=contacts,proto3" json:"contacts,omitempty"`
	Addresses            []*AddressObject  `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProfileObject) Reset()         { *m = ProfileObject{} }
func (m *ProfileObject) String() string { return proto.CompactTextString(m) }
func (*ProfileObject) ProtoMessage()    {}
func (*ProfileObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{2}
}

func (m *ProfileObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileObject.Unmarshal(m, b)
}
func (m *ProfileObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileObject.Marshal(b, m, deterministic)
}
func (m *ProfileObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileObject.Merge(m, src)
}
func (m *ProfileObject) XXX_Size() int {
	return xxx_messageInfo_ProfileObject.Size(m)
}
func (m *ProfileObject) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileObject.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileObject proto.InternalMessageInfo

func (m *ProfileObject) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProfileObject) GetType() ProfileType {
	if m != nil {
		return m.Type
	}
	return ProfileType_PERSON
}

func (m *ProfileObject) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ProfileObject) GetContacts() []*ContactObject {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *ProfileObject) GetAddresses() []*AddressObject {
	if m != nil {
		return m.Addresses
	}
	return nil
}

// The request message containing the profile's hash
type ProfileIDRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileIDRequest) Reset()         { *m = ProfileIDRequest{} }
func (m *ProfileIDRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileIDRequest) ProtoMessage()    {}
func (*ProfileIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{3}
}

func (m *ProfileIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileIDRequest.Unmarshal(m, b)
}
func (m *ProfileIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileIDRequest.Marshal(b, m, deterministic)
}
func (m *ProfileIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileIDRequest.Merge(m, src)
}
func (m *ProfileIDRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileIDRequest.Size(m)
}
func (m *ProfileIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileIDRequest proto.InternalMessageInfo

func (m *ProfileIDRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// The request message containing the profile's hash
type ProfileSearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Properties           []string `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileSearchRequest) Reset()         { *m = ProfileSearchRequest{} }
func (m *ProfileSearchRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileSearchRequest) ProtoMessage()    {}
func (*ProfileSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{4}
}

func (m *ProfileSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileSearchRequest.Unmarshal(m, b)
}
func (m *ProfileSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileSearchRequest.Marshal(b, m, deterministic)
}
func (m *ProfileSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileSearchRequest.Merge(m, src)
}
func (m *ProfileSearchRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileSearchRequest.Size(m)
}
func (m *ProfileSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileSearchRequest proto.InternalMessageInfo

func (m *ProfileSearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *ProfileSearchRequest) GetProperties() []string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ProfileSearchRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ProfileSearchRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// The request message containing the profile's hash
type ProfileMergeRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	MergeID              string   `protobuf:"bytes,2,opt,name=mergeID,proto3" json:"mergeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileMergeRequest) Reset()         { *m = ProfileMergeRequest{} }
func (m *ProfileMergeRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileMergeRequest) ProtoMessage()    {}
func (*ProfileMergeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{5}
}

func (m *ProfileMergeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileMergeRequest.Unmarshal(m, b)
}
func (m *ProfileMergeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileMergeRequest.Marshal(b, m, deterministic)
}
func (m *ProfileMergeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileMergeRequest.Merge(m, src)
}
func (m *ProfileMergeRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileMergeRequest.Size(m)
}
func (m *ProfileMergeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileMergeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileMergeRequest proto.InternalMessageInfo

func (m *ProfileMergeRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProfileMergeRequest) GetMergeID() string {
	if m != nil {
		return m.MergeID
	}
	return ""
}

// The request message containing the information necessary to create a profile
type ProfileCreateRequest struct {
	ID                   string            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 ProfileType       `protobuf:"varint,2,opt,name=type,proto3,enum=profile.ProfileType" json:"type,omitempty"`
	Contact              string            `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	Properties           map[string]string `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProfileCreateRequest) Reset()         { *m = ProfileCreateRequest{} }
func (m *ProfileCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileCreateRequest) ProtoMessage()    {}
func (*ProfileCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{6}
}

func (m *ProfileCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileCreateRequest.Unmarshal(m, b)
}
func (m *ProfileCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileCreateRequest.Marshal(b, m, deterministic)
}
func (m *ProfileCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileCreateRequest.Merge(m, src)
}
func (m *ProfileCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileCreateRequest.Size(m)
}
func (m *ProfileCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileCreateRequest proto.InternalMessageInfo

func (m *ProfileCreateRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProfileCreateRequest) GetType() ProfileType {
	if m != nil {
		return m.Type
	}
	return ProfileType_PERSON
}

func (m *ProfileCreateRequest) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *ProfileCreateRequest) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

// The request message containing the information necessary to create a profile
type ProfileUpdateRequest struct {
	ID                   string            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Properties           map[string]string `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProfileUpdateRequest) Reset()         { *m = ProfileUpdateRequest{} }
func (m *ProfileUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileUpdateRequest) ProtoMessage()    {}
func (*ProfileUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{7}
}

func (m *ProfileUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileUpdateRequest.Unmarshal(m, b)
}
func (m *ProfileUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileUpdateRequest.Marshal(b, m, deterministic)
}
func (m *ProfileUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileUpdateRequest.Merge(m, src)
}
func (m *ProfileUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileUpdateRequest.Size(m)
}
func (m *ProfileUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileUpdateRequest proto.InternalMessageInfo

func (m *ProfileUpdateRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProfileUpdateRequest) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

// The request message containing the information necessary to create a profile
type ProfileAddContactRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Contact              string   `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileAddContactRequest) Reset()         { *m = ProfileAddContactRequest{} }
func (m *ProfileAddContactRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileAddContactRequest) ProtoMessage()    {}
func (*ProfileAddContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{8}
}

func (m *ProfileAddContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileAddContactRequest.Unmarshal(m, b)
}
func (m *ProfileAddContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileAddContactRequest.Marshal(b, m, deterministic)
}
func (m *ProfileAddContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileAddContactRequest.Merge(m, src)
}
func (m *ProfileAddContactRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileAddContactRequest.Size(m)
}
func (m *ProfileAddContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileAddContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileAddContactRequest proto.InternalMessageInfo

func (m *ProfileAddContactRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProfileAddContactRequest) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

// The request message containing the information necessary to create a profile
type ProfileAddAddressRequest struct {
	ID                   string         `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Address              *AddressObject `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProfileAddAddressRequest) Reset()         { *m = ProfileAddAddressRequest{} }
func (m *ProfileAddAddressRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileAddAddressRequest) ProtoMessage()    {}
func (*ProfileAddAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{9}
}

func (m *ProfileAddAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileAddAddressRequest.Unmarshal(m, b)
}
func (m *ProfileAddAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileAddAddressRequest.Marshal(b, m, deterministic)
}
func (m *ProfileAddAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileAddAddressRequest.Merge(m, src)
}
func (m *ProfileAddAddressRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileAddAddressRequest.Size(m)
}
func (m *ProfileAddAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileAddAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileAddAddressRequest proto.InternalMessageInfo

func (m *ProfileAddAddressRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProfileAddAddressRequest) GetAddress() *AddressObject {
	if m != nil {
		return m.Address
	}
	return nil
}

// Request message containing a contact necessary to link to a profile
type ProfileContactRequest struct {
	Contact              string   `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileContactRequest) Reset()         { *m = ProfileContactRequest{} }
func (m *ProfileContactRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileContactRequest) ProtoMessage()    {}
func (*ProfileContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{10}
}

func (m *ProfileContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileContactRequest.Unmarshal(m, b)
}
func (m *ProfileContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileContactRequest.Marshal(b, m, deterministic)
}
func (m *ProfileContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileContactRequest.Merge(m, src)
}
func (m *ProfileContactRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileContactRequest.Size(m)
}
func (m *ProfileContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileContactRequest proto.InternalMessageInfo

func (m *ProfileContactRequest) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func init() {
	proto.RegisterEnum("profile.ContactType", ContactType_name, ContactType_value)
	proto.RegisterEnum("profile.CommunicationLevel", CommunicationLevel_name, CommunicationLevel_value)
	proto.RegisterEnum("profile.ProfileType", ProfileType_name, ProfileType_value)
	proto.RegisterType((*ContactObject)(nil), "profile.ContactObject")
	proto.RegisterType((*AddressObject)(nil), "profile.AddressObject")
	proto.RegisterType((*ProfileObject)(nil), "profile.ProfileObject")
	proto.RegisterMapType((map[string]string)(nil), "profile.ProfileObject.PropertiesEntry")
	proto.RegisterType((*ProfileIDRequest)(nil), "profile.ProfileIDRequest")
	proto.RegisterType((*ProfileSearchRequest)(nil), "profile.ProfileSearchRequest")
	proto.RegisterType((*ProfileMergeRequest)(nil), "profile.ProfileMergeRequest")
	proto.RegisterType((*ProfileCreateRequest)(nil), "profile.ProfileCreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "profile.ProfileCreateRequest.PropertiesEntry")
	proto.RegisterType((*ProfileUpdateRequest)(nil), "profile.ProfileUpdateRequest")
	proto.RegisterMapType((map[string]string)(nil), "profile.ProfileUpdateRequest.PropertiesEntry")
	proto.RegisterType((*ProfileAddContactRequest)(nil), "profile.ProfileAddContactRequest")
	proto.RegisterType((*ProfileAddAddressRequest)(nil), "profile.ProfileAddAddressRequest")
	proto.RegisterType((*ProfileContactRequest)(nil), "profile.ProfileContactRequest")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 891 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x5e, 0x3b, 0x7f, 0xeb, 0x13, 0xb2, 0x35, 0xa7, 0x61, 0x65, 0x96, 0x52, 0x05, 0x23, 0xa1,
	0x68, 0x25, 0xaa, 0xb2, 0xe5, 0x02, 0x21, 0x41, 0xe5, 0x26, 0xa1, 0xb5, 0x48, 0x9c, 0xd5, 0xc4,
	0xbd, 0x40, 0x42, 0x5a, 0xb9, 0xf6, 0x74, 0x6b, 0x48, 0x62, 0xd7, 0x9e, 0x44, 0xe4, 0x29, 0x78,
	0x19, 0xae, 0x10, 0x2f, 0xc0, 0x1b, 0x71, 0x89, 0x3c, 0x33, 0x4e, 0x6c, 0xa7, 0x09, 0x8b, 0x10,
	0x77, 0x73, 0x66, 0xce, 0x7c, 0xe7, 0x3b, 0x3f, 0xdf, 0xd8, 0xd0, 0x89, 0x93, 0xe8, 0x75, 0x38,
	0xa7, 0x8f, 0xe2, 0x24, 0x62, 0x11, 0xb6, 0xa4, 0x69, 0xfe, 0xa9, 0x40, 0x67, 0x10, 0x2d, 0x99,
	0xe7, 0xb3, 0xe9, 0xab, 0x9f, 0xa8, 0xcf, 0xf0, 0x0c, 0x54, 0x7b, 0x68, 0x28, 0x3d, 0xa5, 0xaf,
	0x11, 0xd5, 0x1e, 0x62, 0x1f, 0xea, 0x6c, 0x13, 0x53, 0x43, 0xed, 0x29, 0xfd, 0xb3, 0xab, 0xee,
	0xa3, 0x1c, 0x48, 0xde, 0x72, 0x37, 0x31, 0x25, 0xdc, 0x03, 0xcf, 0xa1, 0x19, 0x50, 0xe6, 0x85,
	0x73, 0xa3, 0xc6, 0x6f, 0x4b, 0x0b, 0x0d, 0x68, 0xad, 0x69, 0x12, 0xbe, 0xa6, 0x81, 0x51, 0xef,
	0x29, 0xfd, 0x53, 0x92, 0x9b, 0x38, 0x86, 0xfb, 0x7e, 0xb4, 0x58, 0xac, 0x96, 0xa1, 0xef, 0xb1,
	0x30, 0x5a, 0xde, 0xcc, 0xe9, 0x9a, 0xce, 0x8d, 0x06, 0x0f, 0xf5, 0x51, 0x21, 0x54, 0xc1, 0x67,
	0x9c, 0xb9, 0x10, 0xf4, 0xf7, 0xf6, 0xcc, 0x5f, 0x55, 0xe8, 0x58, 0x41, 0x90, 0xd0, 0x34, 0x3d,
	0x90, 0x0b, 0x42, 0x7d, 0xe9, 0x2d, 0x44, 0x2e, 0x1a, 0xe1, 0xeb, 0x8c, 0x9d, 0x1f, 0xad, 0x96,
	0x2c, 0xd9, 0x48, 0xda, 0xb9, 0x99, 0x79, 0xfb, 0x21, 0xdb, 0x70, 0xd2, 0x1a, 0xe1, 0xeb, 0x6c,
	0xcf, 0x4b, 0xa8, 0xc7, 0x29, 0x6a, 0x84, 0xaf, 0xb3, 0xbc, 0x53, 0x96, 0x50, 0xca, 0x8c, 0xa6,
	0xc8, 0x5b, 0x58, 0xd8, 0x85, 0xc6, 0x9b, 0x68, 0x95, 0x52, 0xa3, 0xc5, 0xb7, 0x85, 0x81, 0x17,
	0x70, 0x1a, 0x47, 0x29, 0xf3, 0xa3, 0x80, 0x1a, 0xa7, 0xfc, 0x60, 0x6b, 0x67, 0x67, 0x73, 0x8f,
	0x85, 0x6c, 0x15, 0x50, 0x43, 0xeb, 0x29, 0x7d, 0x85, 0x6c, 0x6d, 0x7c, 0x00, 0xda, 0x3c, 0x5a,
	0xde, 0x8a, 0x43, 0xe0, 0x87, 0xbb, 0x8d, 0x2c, 0x16, 0xfd, 0x85, 0x25, 0x9e, 0xd1, 0x16, 0xb1,
	0xb8, 0x61, 0xfe, 0xae, 0x42, 0xe7, 0x5a, 0x14, 0xf1, 0x5f, 0x76, 0x57, 0xde, 0x2a, 0x74, 0xf7,
	0x3b, 0x80, 0x38, 0x89, 0x62, 0x9a, 0xb0, 0x90, 0xa6, 0x46, 0xad, 0x57, 0xeb, 0xb7, 0xaf, 0x3e,
	0xab, 0xfa, 0x8b, 0x28, 0x99, 0x25, 0x1d, 0x47, 0x59, 0x25, 0x49, 0xe1, 0x26, 0x5e, 0xc1, 0xa9,
	0x2f, 0x46, 0x27, 0x35, 0xea, 0x1c, 0xe5, 0xbc, 0x3a, 0x53, 0x02, 0x85, 0x6c, 0xfd, 0xf0, 0x4b,
	0xd0, 0x3c, 0xd1, 0x58, 0x9a, 0x1a, 0x8d, 0xca, 0xa5, 0x52, 0xcb, 0xc9, 0xce, 0xf1, 0xe2, 0x1b,
	0xb8, 0x57, 0x21, 0x82, 0x3a, 0xd4, 0x7e, 0xa6, 0x1b, 0x99, 0x7f, 0xb6, 0xcc, 0x0a, 0xb7, 0xf6,
	0xe6, 0xab, 0x7c, 0x26, 0x84, 0xf1, 0xb5, 0xfa, 0x95, 0x62, 0x9a, 0xa0, 0xcb, 0xac, 0xec, 0x21,
	0xa1, 0x6f, 0x57, 0x34, 0xdd, 0x2b, 0x9f, 0xb9, 0x86, 0xae, 0xf4, 0x99, 0x51, 0x2f, 0xf1, 0xdf,
	0xe4, 0x7e, 0x5d, 0x68, 0xbc, 0x5d, 0xd1, 0x24, 0x8f, 0x24, 0x0c, 0x7c, 0x58, 0x2a, 0xa1, 0xda,
	0xab, 0xf5, 0xb5, 0x52, 0x69, 0x10, 0xea, 0xb1, 0x77, 0x4b, 0xf9, 0x1c, 0x36, 0x08, 0x5f, 0x67,
	0x48, 0x7c, 0x1e, 0xf9, 0x14, 0x36, 0x88, 0x30, 0xcc, 0xa7, 0x70, 0x5f, 0xc6, 0x9d, 0xd0, 0xe4,
	0x96, 0x1e, 0xa0, 0x97, 0xcd, 0xf6, 0x22, 0x3b, 0xb7, 0x87, 0x32, 0xbd, 0xdc, 0x34, 0xff, 0x52,
	0xb6, 0xcc, 0x07, 0x09, 0xf5, 0xd8, 0x41, 0x88, 0xbb, 0x0f, 0x08, 0x17, 0x12, 0x6f, 0xd8, 0x4e,
	0x48, 0xdc, 0xc4, 0x49, 0x29, 0x6f, 0xd1, 0xf4, 0xcf, 0xab, 0x48, 0x25, 0x1a, 0xc7, 0x26, 0xe8,
	0xbf, 0xf6, 0xf5, 0xb7, 0x5d, 0xea, 0x2f, 0xe3, 0xe0, 0x48, 0xea, 0x77, 0xa2, 0x5d, 0x82, 0xf8,
	0x3f, 0x69, 0x0f, 0xc1, 0x90, 0x21, 0xad, 0x20, 0x90, 0x42, 0x39, 0xd2, 0xf7, 0xbc, 0x15, 0x6a,
	0xa9, 0x15, 0xe6, 0x8f, 0x45, 0x14, 0xa9, 0x9c, 0x43, 0x28, 0x8f, 0xa1, 0x25, 0xc5, 0xc4, 0x51,
	0x0e, 0x6b, 0x2e, 0x77, 0x33, 0xbf, 0x80, 0x0f, 0xf2, 0x6e, 0x96, 0x09, 0x16, 0x08, 0x29, 0x25,
	0x42, 0x97, 0x9f, 0x42, 0xbb, 0xf0, 0x25, 0x41, 0x0d, 0x1a, 0xa3, 0x89, 0x65, 0x8f, 0xf5, 0x93,
	0x6c, 0x79, 0xfd, 0x62, 0xea, 0x8c, 0x74, 0xe5, 0x72, 0x09, 0xb8, 0xff, 0x0d, 0xc0, 0x16, 0xd4,
	0xac, 0x71, 0xe6, 0x79, 0x0e, 0x68, 0x3b, 0xee, 0x88, 0x38, 0xd6, 0xf8, 0x66, 0x62, 0x91, 0xef,
	0x47, 0xae, 0xed, 0x3c, 0xd7, 0x15, 0xec, 0x82, 0x6e, 0x4f, 0xae, 0xa7, 0xc4, 0xb5, 0x1c, 0xf7,
	0xc6, 0x1a, 0x8f, 0x88, 0x3b, 0xd3, 0x55, 0x7c, 0x1f, 0x3a, 0xb3, 0x1f, 0x66, 0xee, 0x68, 0x92,
	0x6f, 0xd5, 0xf0, 0x0c, 0xc0, 0x99, 0xde, 0x0c, 0xa6, 0x8e, 0x6b, 0x0d, 0x5c, 0xbd, 0x7e, 0xf9,
	0x04, 0xda, 0x85, 0xf9, 0x46, 0x80, 0xe6, 0xf5, 0x88, 0xcc, 0xa6, 0x8e, 0x7e, 0x82, 0xf7, 0xa0,
	0x6d, 0x3b, 0x33, 0xd7, 0x76, 0x5f, 0xba, 0xf6, 0xd4, 0xd1, 0x95, 0x8c, 0xc5, 0xb3, 0xa9, 0xab,
	0xab, 0x57, 0x7f, 0xd4, 0xe1, 0x6c, 0xfb, 0x18, 0x24, 0xeb, 0xd0, 0xa7, 0xf8, 0x2d, 0xb4, 0x9e,
	0x53, 0xf6, 0x6c, 0x63, 0x0f, 0xf1, 0xc3, 0xea, 0xe0, 0x6c, 0x1f, 0x95, 0x8b, 0xf3, 0x77, 0xbf,
	0xa2, 0xe6, 0x09, 0xbe, 0x80, 0xf7, 0xf8, 0x7d, 0x59, 0x21, 0x7c, 0xb8, 0x27, 0x9a, 0x52, 0x99,
	0x8f, 0x20, 0x0d, 0xa0, 0x29, 0x5e, 0x28, 0xfc, 0xb8, 0xea, 0x53, 0x7a, 0xb9, 0x0e, 0x43, 0x3c,
	0x56, 0xf0, 0x29, 0x34, 0xf8, 0x73, 0x83, 0x0f, 0xaa, 0x4e, 0xc5, 0x57, 0xe8, 0x08, 0x0b, 0x0b,
	0x9a, 0x42, 0xe6, 0xfb, 0x2c, 0x4a, 0xf2, 0x3f, 0x0e, 0x21, 0x24, 0xb7, 0x0f, 0x51, 0x92, 0xe2,
	0x11, 0x08, 0x1b, 0x60, 0x27, 0x21, 0xfc, 0xa4, 0xea, 0xb7, 0x27, 0xaf, 0x7f, 0x84, 0x92, 0x6a,
	0x78, 0x27, 0x54, 0x59, 0x63, 0x87, 0xa1, 0x5e, 0x35, 0xf9, 0x9f, 0xd9, 0x93, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xe9, 0x6a, 0x65, 0x3a, 0xaa, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileServiceClient is the grpc API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	// Obtains a profile by its hash
	GetByID(ctx context.Context, in *ProfileIDRequest, opts ...grpc.CallOption) (*ProfileObject, error)
	// Obtains a profile by its hash
	GetByContact(ctx context.Context, in *ProfileContactRequest, opts ...grpc.CallOption) (*ProfileObject, error)
	// Obtains a profile by its hash
	Search(ctx context.Context, in *ProfileSearchRequest, opts ...grpc.CallOption) (ProfileService_SearchClient, error)
	// Uses data found in the profile from mergeHash to update the current profile.
	Merge(ctx context.Context, in *ProfileMergeRequest, opts ...grpc.CallOption) (*ProfileObject, error)
	// Creates a new profile based on the request.
	Create(ctx context.Context, in *ProfileCreateRequest, opts ...grpc.CallOption) (*ProfileObject, error)
	// Creates a new profile based on the request.
	Update(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileObject, error)
	// Adds a new contact based on the request/this leads to automatic verification.
	AddContact(ctx context.Context, in *ProfileAddContactRequest, opts ...grpc.CallOption) (*ProfileObject, error)
	// Adds a new address based on the request.
	AddAddress(ctx context.Context, in *ProfileAddAddressRequest, opts ...grpc.CallOption) (*ProfileObject, error)
}

type profileServiceClient struct {
	cc *grpc.ClientConn
}

func NewProfileServiceClient(cc *grpc.ClientConn) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) GetByID(ctx context.Context, in *ProfileIDRequest, opts ...grpc.CallOption) (*ProfileObject, error) {
	out := new(ProfileObject)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetByContact(ctx context.Context, in *ProfileContactRequest, opts ...grpc.CallOption) (*ProfileObject, error) {
	out := new(ProfileObject)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/GetByContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Search(ctx context.Context, in *ProfileSearchRequest, opts ...grpc.CallOption) (ProfileService_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfileService_serviceDesc.Streams[0], "/profile.ProfileService/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &profileServiceSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfileService_SearchClient interface {
	Recv() (*ProfileObject, error)
	grpc.ClientStream
}

type profileServiceSearchClient struct {
	grpc.ClientStream
}

func (x *profileServiceSearchClient) Recv() (*ProfileObject, error) {
	m := new(ProfileObject)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *profileServiceClient) Merge(ctx context.Context, in *ProfileMergeRequest, opts ...grpc.CallOption) (*ProfileObject, error) {
	out := new(ProfileObject)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/Merge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Create(ctx context.Context, in *ProfileCreateRequest, opts ...grpc.CallOption) (*ProfileObject, error) {
	out := new(ProfileObject)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Update(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileObject, error) {
	out := new(ProfileObject)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) AddContact(ctx context.Context, in *ProfileAddContactRequest, opts ...grpc.CallOption) (*ProfileObject, error) {
	out := new(ProfileObject)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/AddContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) AddAddress(ctx context.Context, in *ProfileAddAddressRequest, opts ...grpc.CallOption) (*ProfileObject, error) {
	out := new(ProfileObject)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/AddAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	// Obtains a profile by its hash
	GetByID(context.Context, *ProfileIDRequest) (*ProfileObject, error)
	// Obtains a profile by its hash
	GetByContact(context.Context, *ProfileContactRequest) (*ProfileObject, error)
	// Obtains a profile by its hash
	Search(*ProfileSearchRequest, ProfileService_SearchServer) error
	// Uses data found in the profile from mergeHash to update the current profile.
	Merge(context.Context, *ProfileMergeRequest) (*ProfileObject, error)
	// Creates a new profile based on the request.
	Create(context.Context, *ProfileCreateRequest) (*ProfileObject, error)
	// Creates a new profile based on the request.
	Update(context.Context, *ProfileUpdateRequest) (*ProfileObject, error)
	// Adds a new contact based on the request/this leads to automatic verification.
	AddContact(context.Context, *ProfileAddContactRequest) (*ProfileObject, error)
	// Adds a new address based on the request.
	AddAddress(context.Context, *ProfileAddAddressRequest) (*ProfileObject, error)
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) GetByID(ctx context.Context, req *ProfileIDRequest) (*ProfileObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (*UnimplementedProfileServiceServer) GetByContact(ctx context.Context, req *ProfileContactRequest) (*ProfileObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByContact not implemented")
}
func (*UnimplementedProfileServiceServer) Search(req *ProfileSearchRequest, srv ProfileService_SearchServer) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedProfileServiceServer) Merge(ctx context.Context, req *ProfileMergeRequest) (*ProfileObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Merge not implemented")
}
func (*UnimplementedProfileServiceServer) Create(ctx context.Context, req *ProfileCreateRequest) (*ProfileObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedProfileServiceServer) Update(ctx context.Context, req *ProfileUpdateRequest) (*ProfileObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedProfileServiceServer) AddContact(ctx context.Context, req *ProfileAddContactRequest) (*ProfileObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContact not implemented")
}
func (*UnimplementedProfileServiceServer) AddAddress(ctx context.Context, req *ProfileAddAddressRequest) (*ProfileObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAddress not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetByID(ctx, req.(*ProfileIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetByContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetByContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/GetByContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetByContact(ctx, req.(*ProfileContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProfileSearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfileServiceServer).Search(m, &profileServiceSearchServer{stream})
}

type ProfileService_SearchServer interface {
	Send(*ProfileObject) error
	grpc.ServerStream
}

type profileServiceSearchServer struct {
	grpc.ServerStream
}

func (x *profileServiceSearchServer) Send(m *ProfileObject) error {
	return x.ServerStream.SendMsg(m)
}

func _ProfileService_Merge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileMergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Merge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/Merge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Merge(ctx, req.(*ProfileMergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Create(ctx, req.(*ProfileCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Update(ctx, req.(*ProfileUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_AddContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileAddContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).AddContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/AddContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).AddContact(ctx, req.(*ProfileAddContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_AddAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileAddAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).AddAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/AddAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).AddAddress(ctx, req.(*ProfileAddAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "profile.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByID",
			Handler:    _ProfileService_GetByID_Handler,
		},
		{
			MethodName: "GetByContact",
			Handler:    _ProfileService_GetByContact_Handler,
		},
		{
			MethodName: "Merge",
			Handler:    _ProfileService_Merge_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ProfileService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProfileService_Update_Handler,
		},
		{
			MethodName: "AddContact",
			Handler:    _ProfileService_AddContact_Handler,
		},
		{
			MethodName: "AddAddress",
			Handler:    _ProfileService_AddAddress_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _ProfileService_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "profile.proto",
}
