// Copyright 2023-2026 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: settings/v1/settings.proto

package settingsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/antinvestor/common/v1"
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Setting represents a hierarchical key for configuration lookup.
// Supports multi-level scoping for flexible configuration management.
type Setting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                         // Setting name (e.g., "theme", "max_upload_size")
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`                     // Object type scope (e.g., "user", "organization", "application")
	ObjectId      string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"` // Specific object instance ID (for instance-level settings)
	Lang          string                 `protobuf:"bytes,4,opt,name=lang,proto3" json:"lang,omitempty"`                         // Language code for localized settings (ISO 639-1)
	Module        string                 `protobuf:"bytes,5,opt,name=module,proto3" json:"module,omitempty"`                     // Module or feature scope (e.g., "billing", "notifications")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting) Reset() {
	*x = Setting{}
	mi := &file_settings_v1_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting) ProtoMessage() {}

func (x *Setting) ProtoReflect() protoreflect.Message {
	mi := &file_settings_v1_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting.ProtoReflect.Descriptor instead.
func (*Setting) Descriptor() ([]byte, []int) {
	return file_settings_v1_settings_proto_rawDescGZIP(), []int{0}
}

func (x *Setting) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Setting) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *Setting) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *Setting) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *Setting) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

// SettingObject represents a stored setting with its value and metadata.
type SettingObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // Unique identifier for this setting instance
	Key           *Setting               `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`         // Hierarchical key identifying the setting
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`     // Setting value (JSON string for complex values)
	Updated       string                 `protobuf:"bytes,4,opt,name=updated,proto3" json:"updated,omitempty"` // Last update timestamp (RFC3339)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingObject) Reset() {
	*x = SettingObject{}
	mi := &file_settings_v1_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingObject) ProtoMessage() {}

func (x *SettingObject) ProtoReflect() protoreflect.Message {
	mi := &file_settings_v1_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingObject.ProtoReflect.Descriptor instead.
func (*SettingObject) Descriptor() ([]byte, []int) {
	return file_settings_v1_settings_proto_rawDescGZIP(), []int{1}
}

func (x *SettingObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SettingObject) GetKey() *Setting {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SettingObject) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SettingObject) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

// GetRequest retrieves a single setting value.
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Setting               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // Setting key to retrieve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_settings_v1_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settings_v1_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_settings_v1_settings_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() *Setting {
	if x != nil {
		return x.Key
	}
	return nil
}

// GetResponse returns the requested setting.
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SettingObject         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // The requested setting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_settings_v1_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settings_v1_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_settings_v1_settings_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetData() *SettingObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SearchResponse returns settings matching search criteria.
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*SettingObject       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // List of matching settings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_settings_v1_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settings_v1_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_settings_v1_settings_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetData() []*SettingObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// ListRequest retrieves all settings matching a partial key.
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Setting               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // Partial key for filtering (empty fields match all)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_settings_v1_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settings_v1_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_settings_v1_settings_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetKey() *Setting {
	if x != nil {
		return x.Key
	}
	return nil
}

// ListResponse returns matching settings.
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*SettingObject       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // List of matching settings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_settings_v1_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settings_v1_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_settings_v1_settings_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetData() []*SettingObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SetRequest creates or updates a setting value.
type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Setting               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // Setting key to set
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // New value for the setting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_settings_v1_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settings_v1_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_settings_v1_settings_proto_rawDescGZIP(), []int{7}
}

func (x *SetRequest) GetKey() *Setting {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// SetResponse returns the updated setting.
type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SettingObject         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // The updated setting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_settings_v1_settings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settings_v1_settings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_settings_v1_settings_proto_rawDescGZIP(), []int{8}
}

func (x *SetResponse) GetData() *SettingObject {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_settings_v1_settings_proto protoreflect.FileDescriptor

const file_settings_v1_settings_proto_rawDesc = "" +
	"\n" +
	"\x1asettings/v1/settings.proto\x12\vsettings.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16common/v1/common.proto\x1a\x1bcommon/v1/permissions.proto\x1a$gnostic/openapi/v3/annotations.proto\"\xcb\x01\n" +
	"\aSetting\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x02R\x04name\x12\"\n" +
	"\x06object\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xd8\x01\x01r\x02\x10\x02R\x06object\x12;\n" +
	"\tobject_id\x18\x03 \x01(\tB\x1e\xbaH\x1b\xd8\x01\x01r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,40}R\bobjectId\x12\x1e\n" +
	"\x04lang\x18\x04 \x01(\tB\n" +
	"\xbaH\a\xd8\x01\x01r\x02\x10\x02R\x04lang\x12\"\n" +
	"\x06module\x18\x05 \x01(\tB\n" +
	"\xbaH\a\xd8\x01\x01r\x02\x10\x03R\x06module\"\x94\x01\n" +
	"\rSettingObject\x12+\n" +
	"\x02id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,40}R\x02id\x12&\n" +
	"\x03key\x18\x02 \x01(\v2\x14.settings.v1.SettingR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x18\n" +
	"\aupdated\x18\x04 \x01(\tR\aupdated\"4\n" +
	"\n" +
	"GetRequest\x12&\n" +
	"\x03key\x18\x01 \x01(\v2\x14.settings.v1.SettingR\x03key\"=\n" +
	"\vGetResponse\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.settings.v1.SettingObjectR\x04data\"@\n" +
	"\x0eSearchResponse\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.settings.v1.SettingObjectR\x04data\"5\n" +
	"\vListRequest\x12&\n" +
	"\x03key\x18\x01 \x01(\v2\x14.settings.v1.SettingR\x03key\">\n" +
	"\fListResponse\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.settings.v1.SettingObjectR\x04data\"J\n" +
	"\n" +
	"SetRequest\x12&\n" +
	"\x03key\x18\x01 \x01(\v2\x14.settings.v1.SettingR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"=\n" +
	"\vSetResponse\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.settings.v1.SettingObjectR\x04data2\xaa\v\n" +
	"\x0fSettingsService\x12\xb7\x02\n" +
	"\x03Get\x12\x17.settings.v1.GetRequest\x1a\x18.settings.v1.GetResponse\"\xfc\x01\xbaG\xe3\x01\n" +
	"\bSettings\x12\x13Get a setting value\x1a\xb5\x01Retrieves a single setting value by its hierarchical key. The service returns the most specific matching setting based on the key hierarchy (instance-level > object-level > global).*\n" +
	"getSetting\x82\xb5\x18\x0e\n" +
	"\fsetting_view\x90\x02\x01\x12\xc9\x02\n" +
	"\x04List\x12\x18.settings.v1.ListRequest\x1a\x19.settings.v1.ListResponse\"\x89\x02\xbaG\xf0\x01\n" +
	"\bSettings\x12\x1cList settings by partial key\x1a\xb7\x01Retrieves all settings matching a partial key. Empty fields in the key act as wildcards, allowing flexible queries (e.g., all settings for an object type, all settings in a language).*\flistSettings\x82\xb5\x18\x0e\n" +
	"\fsetting_view\x90\x02\x010\x01\x12\x99\x02\n" +
	"\x06Search\x12\x18.common.v1.SearchRequest\x1a\x1b.settings.v1.SearchResponse\"\xd5\x01\xbaG\xbc\x01\n" +
	"\bSettings\x12\x0fSearch settings\x1a\x8e\x01Searches for settings matching specified criteria including full-text search on names and values, date range filtering, and custom properties.*\x0esearchSettings\x82\xb5\x18\x0e\n" +
	"\fsetting_view\x90\x02\x010\x01\x12\xa1\x02\n" +
	"\x03Set\x12\x17.settings.v1.SetRequest\x1a\x18.settings.v1.SetResponse\"\xe6\x01\xbaG\xce\x01\n" +
	"\bSettings\x12\x1aCreate or update a setting\x1a\x99\x01Creates or updates a setting value. If the setting exists, it is updated with the new value and timestamp. If it doesn't exist, a new setting is created.*\n" +
	"setSetting\x82\xb5\x18\x10\n" +
	"\x0esetting_manage\x1a\xd0\x01\x82\xb5\x18\xcb\x01\n" +
	"\x0fservice_setting\x12\fsetting_view\x12\x0esetting_manage\x1a \b\x01\x12\fsetting_view\x12\x0esetting_manage\x1a \b\x02\x12\fsetting_view\x12\x0esetting_manage\x1a\x10\b\x03\x12\fsetting_view\x1a\x10\b\x04\x12\fsetting_view\x1a\x10\b\x05\x12\fsetting_view\x1a \b\x06\x12\fsetting_view\x12\x0esetting_manageB\xac\x06\xbaG\xfc\x04\x12\xd0\x04\n" +
	"\x10Settings Service\x12\x8d\x03The Settings Service provides hierarchical configuration management for applications and services. It supports multi-level scoping (global, object-level, instance-level), localization, and module-specific settings. Settings can be organized by object type, object ID, language, and module, enabling flexible configuration management for multi-tenant applications with internationalization support.\"Y\n" +
	"\x10Ant Investor Ltd\x12/https://github.com/antinvestor/service-settings\x1a\x14info@antinvestor.com*I\n" +
	"\x0eApache License\x127https://github.com/antinvestor/apis/blob/master/LICENSE2\x06v1.0.0*':%\n" +
	"#\n" +
	"\n" +
	"BearerAuth\x12\x15\n" +
	"\x13\n" +
	"\x04http*\x06bearer2\x03JWT\n" +
	"\x0fcom.settings.v1B\rSettingsProtoP\x01Z=github.com/antinvestor/service-profile/settings/v1;settingsv1\xa2\x02\x03SXX\xaa\x02\vSettings.V1\xca\x02\vSettings\\V1\xe2\x02\x17Settings\\V1\\GPBMetadata\xea\x02\fSettings::V1b\x06proto3"

var (
	file_settings_v1_settings_proto_rawDescOnce sync.Once
	file_settings_v1_settings_proto_rawDescData []byte
)

func file_settings_v1_settings_proto_rawDescGZIP() []byte {
	file_settings_v1_settings_proto_rawDescOnce.Do(func() {
		file_settings_v1_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settings_v1_settings_proto_rawDesc), len(file_settings_v1_settings_proto_rawDesc)))
	})
	return file_settings_v1_settings_proto_rawDescData
}

var file_settings_v1_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_settings_v1_settings_proto_goTypes = []any{
	(*Setting)(nil),          // 0: settings.v1.Setting
	(*SettingObject)(nil),    // 1: settings.v1.SettingObject
	(*GetRequest)(nil),       // 2: settings.v1.GetRequest
	(*GetResponse)(nil),      // 3: settings.v1.GetResponse
	(*SearchResponse)(nil),   // 4: settings.v1.SearchResponse
	(*ListRequest)(nil),      // 5: settings.v1.ListRequest
	(*ListResponse)(nil),     // 6: settings.v1.ListResponse
	(*SetRequest)(nil),       // 7: settings.v1.SetRequest
	(*SetResponse)(nil),      // 8: settings.v1.SetResponse
	(*v1.SearchRequest)(nil), // 9: common.v1.SearchRequest
}
var file_settings_v1_settings_proto_depIdxs = []int32{
	0,  // 0: settings.v1.SettingObject.key:type_name -> settings.v1.Setting
	0,  // 1: settings.v1.GetRequest.key:type_name -> settings.v1.Setting
	1,  // 2: settings.v1.GetResponse.data:type_name -> settings.v1.SettingObject
	1,  // 3: settings.v1.SearchResponse.data:type_name -> settings.v1.SettingObject
	0,  // 4: settings.v1.ListRequest.key:type_name -> settings.v1.Setting
	1,  // 5: settings.v1.ListResponse.data:type_name -> settings.v1.SettingObject
	0,  // 6: settings.v1.SetRequest.key:type_name -> settings.v1.Setting
	1,  // 7: settings.v1.SetResponse.data:type_name -> settings.v1.SettingObject
	2,  // 8: settings.v1.SettingsService.Get:input_type -> settings.v1.GetRequest
	5,  // 9: settings.v1.SettingsService.List:input_type -> settings.v1.ListRequest
	9,  // 10: settings.v1.SettingsService.Search:input_type -> common.v1.SearchRequest
	7,  // 11: settings.v1.SettingsService.Set:input_type -> settings.v1.SetRequest
	3,  // 12: settings.v1.SettingsService.Get:output_type -> settings.v1.GetResponse
	6,  // 13: settings.v1.SettingsService.List:output_type -> settings.v1.ListResponse
	4,  // 14: settings.v1.SettingsService.Search:output_type -> settings.v1.SearchResponse
	8,  // 15: settings.v1.SettingsService.Set:output_type -> settings.v1.SetResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_settings_v1_settings_proto_init() }
func file_settings_v1_settings_proto_init() {
	if File_settings_v1_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settings_v1_settings_proto_rawDesc), len(file_settings_v1_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settings_v1_settings_proto_goTypes,
		DependencyIndexes: file_settings_v1_settings_proto_depIdxs,
		MessageInfos:      file_settings_v1_settings_proto_msgTypes,
	}.Build()
	File_settings_v1_settings_proto = out.File
	file_settings_v1_settings_proto_goTypes = nil
	file_settings_v1_settings_proto_depIdxs = nil
}
